#####################################################
# 1st step - install nordpool component in HACS 
# 2nd step - add the code to configuration.yaml
# 3rd step - adjust your "additional_costs:" accordingly to your electric transmission net tariffs
# lastly - this code has no input to handle holidays (i.e. 'red days'. hopefully it can be solved in some way - soon (?)
# still no solution to fixed monthly fees that is only SEK/h , this has to be handled separated in some way.
##########################################################
#    check your rates/taxes to these settings
#    additional_costs: '{% set s = {
#    "hourly_fixed_cost": 0.45,
#    "winter_night": 0.2563,
#    "winter_day": 0.2563,
#    "summer_day": 0.2563,
#    "summer_night": 0.2563,
#    "cert": 0.0
#####################################################

#
nordpool:
sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currecy
    currency: "SEK"

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "SE3"

    # How many decimals to use in the display of the price
    precision: 3

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: '{% set s = {
    "hourly_fixed_cost": 0.45,
    "winter_night": 0.2563,
    "winter_day": 0.2563,
    "summer_day": 0.2563,
    "summer_night": 0.2563,
    "cert": 0.0
}
%}
{% if now().month >= 4 and now().month <11 and now().isoweekday >5 %}
    {% if now().hour >=6 and now().hour <22 %}
        {{s.summer_day+s.hourly_fixed_cost+s.cert|float}}
    {% else %}
        {{s.night+s.hourly_fixed_cost+s.cert|float}}
    {% endif %}
{% else %}
    {% if now().hour >=6 and now().hour <22 %}
        {{s.winter_day+s.hourly_fixed_cost+s.cert|float}}
    {%else%}
        {{s.winter_night+s.hourly_fixed_cost+s.cert|float}}
    {% endif %}
{% endif %}'
#################################################################
